framework:
    cache:
        prefix_seed: alexandrebonnin/back
        app: cache.adapter.filesystem
        pools:
            doctrine.result_cache_pool:
                adapter: cache.adapter.filesystem
                default_lifetime: 3600
            api_response_cache:
                adapter: cache.adapter.filesystem
                default_lifetime: 300
            user_cache:
                adapter: cache.adapter.filesystem
                default_lifetime: 1800
            image_cache:
                adapter: cache.adapter.filesystem
                default_lifetime: 86400
