doctrine:
    dbal:
        override_url: true
        url: '%env(resolve:DATABASE_URL)%'
        server_version: '13'
        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci
        types:
            json: Doctrine\DBAL\Types\JsonType
        logging: '%kernel.debug%'
        profiling: '%kernel.debug%'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
        query_cache_driver:
            type: pool
            pool: cache.app
        result_cache_driver:
            type: pool
            pool: cache.app
        metadata_cache_driver:
            type: pool
            pool: cache.app
        second_level_cache:
            enabled: true
            region_cache_driver:
                type: pool
                pool: cache.app
            regions:
                default:
                    lifetime: 3600
                    cache_driver:
                        type: pool
                        pool: cache.app
