gesdinet_jwt_refresh_token:
  ttl: 2592000 # 30 jours
  user_identity_field: id
  user_provider: security.user.provider.concrete.in_database
  refresh_token_class: App\Entity\RefreshToken
  refresh_token_ttl: 2592000 # 30 jours
  refresh_token_parameter_name: refresh_token
  refresh_token_extractors:
    request_body:
      enabled: true
    query_string:
      enabled: false
    cookie:
      enabled: false
  single_use: true
  rotate_tokens: true