gesdinet_jwt_refresh_token:
  ttl: 2592000 # 30 jours
  user_identity_field: id
  user_provider: security.user.provider.concrete.in_database
  refresh_token_class: App\Entity\RefreshToken
  single_use: true
  token_parameter_name: refresh_token
  return_expiration: true
  return_expiration_parameter_name: expires_in