knpu_oauth2_client:
    clients:
        google:
            type: google
            client_id: '%env(GOOGLE_CLIENT_ID)%'
            client_secret: '%env(GOOGLE_CLIENT_SECRET)%'
            redirect_route: connect_google_check
            redirect_params: {}
        github:
            type: github
            client_id: '%env(GITHUB_CLIENT_ID)%'
            client_secret: '%env(GITHUB_CLIENT_SECRET)%'
            redirect_route: connect_github_check
            redirect_params: {}
    http_client: ~
    cache: cache.app
    cache_key: 'oauth2_client'
    cache_lifetime: 3600
    cache_headers: true
    cache_headers_ttl: 3600
    cache_headers_private: true
    cache_headers_no_cache: false
    cache_headers_must_revalidate: true
    cache_headers_proxy_revalidate: false
    cache_headers_max_age: 3600
    cache_headers_s_maxage: 3600