lexik_jwt_authentication:
    private_key_path: '%env(resolve:JWT_PRIVATE_KEY_PATH)%'  # Remplacer private_key par private_key_path
    public_key_path: '%env(resolve:JWT_PUBLIC_KEY_PATH)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    token_ttl: 3600
    user_identity_field: id