services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    restart: always
    environment:
      - APP_ENV=prod
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - ./apache2/default.conf:/etc/apache2/sites-available/000-default.conf
      - /var/projects/env_files/backend.alexandrebonnin.fr.env:/var/www/html/.env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend-alexandrebonnin-fr.rule=Host(`backend.alexandrebonnin.fr`)"
      - "traefik.http.routers.backend-alexandrebonnin-fr.entrypoints=web,websecure"
      - "traefik.http.services.backend-alexandrebonnin-fr.loadbalancer.server.port=80"
      - "traefik.http.routers.backend-alexandrebonnin-fr.tls=true"
      - "traefik.http.routers.backend-alexandrebonnin-fr.tls.certresolver=production"
    networks:
      - traefik_default

networks:
  traefik_default:
    external: true 