services:
  backend-alexandrebonnin-fr:
    container_name: backend-alexandrebonnin-fr
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    working_dir: /var/www
    environment:
      APP_ENV: "${APP_ENV}"
      DATABASE_URL: "${DATABASE_URL}"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - volume_data:/var/www
    networks:
      - traefik_default
      - internal_network

  backend-alexandrebonnin-fr-nginx:
    image: nginx:1.21
    container_name: backend-alexandrebonnin-fr-nginx
    restart: unless-stopped
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend-alexandrebonnin-fr-nginx.rule=Host(`backend.alexandrebonnin.fr`)"
      - "traefik.http.routers.backend-alexandrebonnin-fr-nginx.entrypoints=web,websecure"
      - "traefik.http.services.backend-alexandrebonnin-fr-nginx.loadbalancer.server.port=80"
      - "traefik.http.routers.backend-alexandrebonnin-fr-nginx.tls=true"
      - "traefik.http.routers.backend-alexandrebonnin-fr-nginx.tls.certresolver=production"
    depends_on:
      - backend-alexandrebonnin-fr
    networks:
      - traefik_default
      - internal_network

networks:
  traefik_default:
    external: true
  internal_network:
    driver: bridge

volumes:
  volume_data: