services:
  php:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/var/www/html
      - .env.dev:/var/www/html/.env
      - /var/www/html/vendor
      - /var/www/html/var
    environment:
      - APP_ENV=dev
      - DATABASE_URL=${DATABASE_URL}
      - PHP_IDE_CONFIG=serverName=Docker
      - XDEBUG_CONFIG=client_host=host.docker.internal
    ports:
      - "9003:9003"
    depends_on:
      - database
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - .env.dev:/var/www/html/.env
      - /var/www/html/vendor
      - /var/www/html/var
      - ./nginx/dev.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - app-network

  database:
    container_name: database
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data: 