services:
  backend-alexandrebonnin-fr:
    container_name: backend-alexandrebonnin-fr
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    environment:
      - APP_ENV=dev
      - SYMFONY_ENV=dev
      - DATABASE_URL=${DATABASE_URL}
      - XDEBUG_MODE=debug
      - XDEBUG_CONFIG=client_host=host.docker.internal
    volumes:
      - volume_data:/var/www/html
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - /var/www/html/vendor
      - /var/www/html/var
    depends_on:
      - database

  nginx:
    image: nginx:alpine
    container_name: nginx-backend-alexandrebonnin-fr
    restart: always
    volumes:
      - volume_data:/var/www/html
      - ./docker/nginx/dev.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
    depends_on:
      - backend-alexandrebonnin-fr

  database:
    container_name: database
    image: mariadb:11.7
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  volume_data:
  mysql_data: