server {
    listen 80;
    server_name localhost;

    # Utilisation de variables d'environnement si besoin
    # Par exemple, si tu définis des variables comme APP_HOST et APP_PORT dans docker-compose.yml
    set $app_host $APP_HOST;
    set $app_port $APP_PORT;

    # Redirection HTTP vers HTTPS si nécessaire
    # if ($scheme = http) {
    #     return 301 https://$host$request_uri;
    # }

    location / {
        # Utiliser la variable d'environnement APP_HOST si définie
        proxy_pass http://$app_host:$app_port;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_http_version 1.1;
        proxy_cache_bypass $http_upgrade;
    }

    # Configuration des erreurs et autres options
    error_page  404              /404.html;
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }

    location = /404.html {
        root   /usr/share/nginx/html;
    }
}